repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: semgrep-local
        name: Semgrep Scan
        entry: uv run --directory shopping-assistant semgrep --config .semgrep/rules.yaml --error
        language: system
        types: [python]
        pass_filenames: false
